use super::*;

impl CCodeGen {
    /// Assemble all code sections into the final C output.
    pub(crate) fn assemble(&self) -> String {
        let mut output = Vec::new();

        // Header
        output.push("/* Generated by ore_c_codegen */".to_string());
        output.push("#include <stdint.h>".to_string());
        output.push("#include <stddef.h>".to_string());
        output.push("#include <string.h>".to_string());
        output.push("#include <stdlib.h>".to_string());
        output.push(String::new());

        // Tagged union type for Option/Result
        output.push("typedef struct { int8_t tag; int8_t kind; int64_t val; } OreTaggedUnion;".to_string());
        output.push(String::new());

        // Runtime extern declarations
        output.push("/* Runtime function declarations */".to_string());
        output.extend(runtime_decls::runtime_declarations());
        output.push(String::new());

        // Type definitions (structs)
        if !self.top_level.is_empty() {
            output.push("/* Type definitions */".to_string());
            output.extend(self.top_level.iter().cloned());
            output.push(String::new());
        }

        // Forward declarations
        if !self.forward_decls.is_empty() {
            output.push("/* Forward declarations */".to_string());
            output.extend(self.forward_decls.iter().cloned());
            output.push(String::new());
        }

        // Lambda function bodies
        if !self.lambda_bodies.is_empty() {
            output.push("/* Lambda functions */".to_string());
            output.extend(self.lambda_bodies.iter().cloned());
            output.push(String::new());
        }

        // Main function bodies
        output.push("/* Function definitions */".to_string());
        output.extend(self.lines.iter().cloned());

        output.join("\n")
    }

    /// Emit a main() that calls all test functions (for test-only files).
    pub(crate) fn emit_test_runner_main(&mut self) {
        self.forward_decls.push("int32_t main(void);".to_string());
        self.emit_raw("int32_t main(void) {");
        self.indent = 1;
        self.emit("ore_assert_set_test_mode(1);");
        self.emit("int passed = 0, failed = 0;");
        for i in 0..self.test_names.len() {
            let fn_name = format!("ore_test_{}", i);
            let test_name = Self::escape_c_string(&self.test_names[i]);
            self.emit("ore_assert_check_and_reset();");
            self.emit(&format!("{}();", fn_name));
            self.emit(&format!("if (ore_assert_check_and_reset()) {{ failed++; ore_str_print(ore_str_new(\"  FAIL: {}\", {})); }}", test_name, test_name.len() + 8));
            self.emit(&format!("else {{ passed++; ore_str_print(ore_str_new(\"  PASS: {}\", {})); }}", test_name, test_name.len() + 8));
        }
        self.emit("ore_assert_set_test_mode(0);");
        self.emit("if (failed > 0) return 1;");
        self.emit("return 0;");
        self.indent = 0;
        self.emit_raw("}");
    }
}
